#! /bin/sh

pgregp -x sxhkd > /dev/null || sxhkd &
#picom --config ~/.config/picom/prueba.conf &
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
$HOME/.config/polybar/forest/launch.sh
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#6DF0E9'
bspc config presel_feedback_color '#512da8'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^10'


